const fs = require('fs');
const path = require('path');

const mergedDataPath = path.join(__dirname, 'merged_data.json');
const mergedData = JSON.parse(fs.readFileSync(mergedDataPath, 'utf8'));

// Chemistry dictionary terms
mergedData["chemistry-periodic"] = [
  { word: "Atom", definition: "Basic unit of matter consisting of a dense nucleus surrounded by a cloud of electrons.", etymology: "From Greek 'atomos' (indivisible).", funFact: "An atom is 99.9999999% empty space!", score: 10 },
  { word: "Proton", definition: "Positively charged subatomic particle located in the atomic nucleus.", etymology: "From Greek 'proton' (first).", funFact: "The number of protons determines the atomic identity of an element.", score: 10 },
  { word: "Neutron", definition: "Uncharged neutral subatomic particle located in the atomic nucleus.", etymology: "From Latin 'neuter' (neither one).", funFact: "Neutrons act as nuclear glue preventing positively charged protons from repelling.", score: 10 },
  { word: "Electron", definition: "Negatively charged subatomic particle orbiting the atomic nucleus.", etymology: "From Greek 'elektron' (amber).", funFact: "Electrons travel near the speed of light in probability clouds around the nucleus.", score: 10 },
  { word: "Element", definition: "Pure chemical substance consisting of atoms with the same number of protons.", etymology: "From Latin 'elementum' (first principle).", funFact: "There are 118 known elements on the periodic table.", score: 10 },
  { word: "Compound", definition: "Substance formed when two or more distinct chemical elements are chemically bonded.", etymology: "From Latin 'componere' (to put together).", funFact: "Water (H2O) is a compound with totally different properties than hydrogen and oxygen gas!", score: 10 },
  { word: "Mixture", definition: "Combination of two or more substances that are physically mixed but not chemically bonded.", etymology: "From Latin 'mixtura'.", funFact: "Air is a homogeneous mixture mainly of nitrogen and oxygen gas.", score: 10 },
  { word: "Molecule", definition: "Group of two or more atoms held together by chemical bonds.", etymology: "From Latin 'moles' (mass/small unit).", funFact: "A single drop of water contains about 1.5 sextillion water molecules!", score: 10 },
  { word: "Ion", definition: "Atom or molecule with a net electrical charge due to loss or gain of electrons.", etymology: "From Greek 'ion' (going/wanderer).", funFact: "Ions in dissolved salt solutions allow electricity to flow.", score: 15 },
  { word: "Cation", definition: "Positively charged ion formed when an atom loses electrons.", etymology: "From Greek 'kata' (down) + 'ion'.", funFact: "Sodium (Na+) is a vital cation for nerve signal transmission.", score: 15 },
  { word: "Anion", definition: "Negatively charged ion formed when an atom gains electrons.", etymology: "From Greek 'ana' (up) + 'ion'.", funFact: "Chloride (Cl-) is a common anion found in table salt.", score: 15 },
  { word: "Periodic Table", definition: "Tabular arrangement of chemical elements ordered by atomic number and chemical properties.", etymology: "From Greek 'periodos' (circuit/cycle).", funFact: "Dmitri Mendeleev predicted elements before they were even discovered using the table!", score: 15 },
  { word: "Atomic Number", definition: "Number of protons in the nucleus of an atom determining its element placement.", etymology: "From Greek 'atomos' + Number.", funFact: "Hydrogen has atomic number 1, while Uranium has atomic number 92.", score: 10 },
  { word: "Mass Number", definition: "Total count of protons and neutrons in an atomic nucleus.", etymology: "From Latin 'massa' + Number.", funFact: "Isotopes of an element have the same atomic number but different mass numbers.", score: 15 },
  { word: "Isotope", definition: "Variant of a chemical element with the same proton count but different neutron count.", etymology: "From Greek 'isos' (equal) + 'topos' (place).", funFact: "Carbon-14 is a radioactive isotope used to date ancient organic artifacts.", score: 20 },
  { word: "Valence Electron", definition: "Electron in the outermost shell of an atom participating in chemical bonding.", etymology: "From Latin 'valentia' (power/capacity).", funFact: "Noble gases have full valence shells, making them exceptionally unreactive.", score: 20 },
  { word: "Covalent Bond", definition: "Chemical bond formed when two atoms share pairs of valence electrons.", etymology: "From Latin 'co-' (together) + 'valentia'.", funFact: "Diamond is held together by an extraordinarily strong 3D covalent network.", score: 20 },
  { word: "Ionic Bond", definition: "Electrostatic attraction bond formed between oppositely charged cations and anions.", etymology: "From Greek 'ion' + Bond.", funFact: "Ionic compounds form high-melting-point crystalline lattice structures.", score: 20 },
  { word: "Metallic Bond", definition: "Bonding force arising from electrostatic attraction between metal cations and delocalized sea of electrons.", etymology: "From Greek 'metallon' + Bond.", funFact: "Delocalized sea of electrons gives metals high electrical and thermal conductivity.", score: 20 },
  { word: "Electronegativity", definition: "Chemical property describing an atom's ability to attract shared electrons in a bond.", etymology: "From Greek 'elektron' + Negative.", funFact: "Fluorine is the most electronegative element on the periodic table!", score: 20 },
  { word: "Enthalpy", definition: "Total heat content of a thermodynamic system at constant pressure.", etymology: "From Greek 'enthalpein' (to warm in).", funFact: "Exothermic reactions release enthalpy to the surroundings as heat.", score: 20 },
  { word: "Exothermic", definition: "Chemical process that releases thermal energy to its surroundings.", etymology: "From Greek 'exo' (outside) + 'therme' (heat).", funFact: "Combustion of fuels is a classic exothermic reaction producing heat and light.", score: 15 },
  { word: "Endothermic", definition: "Chemical reaction that absorbs thermal energy from its surroundings.", etymology: "From Greek 'endon' (within) + 'therme' (heat).", funFact: "Photosynthesis is an endothermic reaction absorbing solar energy.", score: 15 },
  { word: "Catalyst", definition: "Substance that increases chemical reaction rate without undergoing permanent chemical change.", etymology: "From Greek 'katalysis' (dissolution/untying).", funFact: "Catalytic converters in cars convert toxic exhaust gases into safer nitrogen and CO2.", score: 20 },
  { word: "Stoichiometry", definition: "Calculation of quantitative relationships between reactants and products in chemical reactions.", etymology: "From Greek 'stoicheion' (element) + 'metron' (measure).", funFact: "Stoichiometry ensures chemical equations obey the Law of Conservation of Mass.", score: 25 },
  { word: "Mole", definition: "SI unit for amount of substance containing exactly 6.022 x 10^23 elementary entities.", etymology: "From German 'Mol', short for 'Molekül' (molecule).", funFact: "One mole of marbles would cover the entire Earth to a depth of 50 miles!", score: 20 },
  { word: "Molarity", definition: "Concentration measure defined as moles of solute per liter of solution.", etymology: "From 'mole' + '-arity'.", funFact: "Standard laboratory acids are often stored as concentrated 12 M solutions.", score: 20 },
  { word: "Concentration", definition: "Amount of a substance present per unit volume of solution.", etymology: "From Latin 'con-' (together) + 'centrum' (center).", funFact: "Higher concentration increases particle collision frequency, speeding up reactions.", score: 15 },
  { word: "Acid", definition: "Chemical species that donates protons (H+ ions) or accepts electron pairs.", etymology: "From Latin 'acidus' (sour).", funFact: "Stomach gastric acid contains hydrochloric acid with a pH around 1.5 to 2.0.", score: 15 },
  { word: "Base", definition: "Chemical species that accepts protons or donates hydroxide ions (OH-) in solution.", etymology: "From Greek 'basis' (foundation/pedestal).", funFact: "Bases feel slippery to the touch because they react with skin oils to form soap.", score: 15 },
  { word: "pH", definition: "Logarithmic scale measuring hydrogen ion concentration in an aqueous solution.", etymology: "Abbreviation for 'Power of Hydrogen'.", funFact: "Each unit change on the pH scale represents a 10-fold change in acidity!", score: 15 },
  { word: "Titration", definition: "Volumetric technique where a solution of known concentration is used to determine an unknown concentration.", etymology: "From French 'titre' (rank/purity).", funFact: "pH indicators like phenolphthalein change color at the exact equivalence point.", score: 20 },
  { word: "Oxidation", definition: "Loss of electrons or increase in oxidation state during a chemical reaction.", etymology: "From French 'oxygèner' (combine with oxygen).", funFact: "Rusting of iron is a slow oxidation process reacting with atmospheric oxygen.", score: 15 },
  { word: "Reduction", definition: "Gain of electrons or decrease in oxidation state during a chemical reaction.", etymology: "From Latin 'reducere' (bring back).", funFact: "Oxidation and reduction ALWAYS occur simultaneously in redox reactions!", score: 15 },
  { word: "Electrolysis", definition: "Decomposition of an ionic compound using a direct electric current.", etymology: "From Greek 'elektron' + 'lysis' (loosening).", funFact: "Electrolysis of water produces pure hydrogen gas at the cathode and oxygen at the anode.", score: 20 },
  { word: "Polymer", definition: "Large macromolecule composed of repeating structural monomer units.", etymology: "From Greek 'poly' (many) + 'meros' (part).", funFact: "DNA, proteins, nylon, and polyethylene plastic are all polymers!", score: 15 },
  { word: "Hydrocarbon", definition: "Organic compound consisting entirely of hydrogen and carbon atoms.", etymology: "From 'hydrogen' + 'carbon'.", funFact: "Crude oil is a complex mixture of hundreds of different hydrocarbon molecules.", score: 15 }
];

// Physics dictionary terms
mergedData["physics-mechanics"] = [
  { word: "Force", definition: "Interaction that changes or tends to change the motion or shape of an object.", etymology: "From Latin 'fortis' (strong).", funFact: "Force is a vector quantity measured in Newtons (N).", score: 10 },
  { word: "Velocity", definition: "Rate of change of displacement with respect to time in a specified direction.", etymology: "From Latin 'velox' (swift).", funFact: "Speed is scalar, but velocity includes direction!", score: 10 },
  { word: "Acceleration", definition: "Rate of change of velocity per unit of time.", etymology: "From Latin 'accelerare' (hasten).", funFact: "Gravity accelerates falling objects on Earth at roughly 9.8 m/s².", score: 10 },
  { word: "Mass", definition: "Quantitative measure of inertia and amount of matter in a physical body.", etymology: "From Greek 'maza' (lump/cake).", funFact: "Your mass stays identical on the Moon, but your weight drops by 83%!", score: 10 },
  { word: "Weight", definition: "Gravitational force exerted on an object's mass.", etymology: "From Old English 'wiht'.", funFact: "Weight = Mass x Gravitational Acceleration (W = mg).", score: 10 },
  { word: "Gravity", definition: "Fundamental force of attraction acting between all masses in the universe.", etymology: "From Latin 'gravitas' (weight/heaviness).", funFact: "General relativity describes gravity as the curvature of spacetime around mass.", score: 15 },
  { word: "Inertia", definition: "Resistance of any physical object to any change in its state of motion.", etymology: "From Latin 'iners' (idle/sluggish).", funFact: "Newton's First Law is also known as the Law of Inertia.", score: 15 },
  { word: "Momentum", definition: "Product of the mass and velocity of a moving object (p = mv).", etymology: "From Latin 'momentum' (movement/impulse).", funFact: "Total momentum is conserved in all closed system collisions!", score: 20 },
  { word: "Friction", definition: "Force resisting the relative motion of solid surfaces, fluid layers, or material elements sliding against each other.", etymology: "From Latin 'fricare' (to rub).", funFact: "Friction converts kinetic energy directly into thermal heat energy.", score: 10 },
  { word: "Work", definition: "Energy transferred to or from an object via the application of force along a displacement.", etymology: "From Old English 'weorc'.", funFact: "No mechanical work is done if force is perpendicular to displacement!", score: 15 },
  { word: "Kinetic Energy", definition: "Energy possessed by an object due to its motion (KE = 1/2 mv²).", etymology: "From Greek 'kinetikos' (moving).", funFact: "Doubling your speed quadruples your car's kinetic stopping distance!", score: 15 },
  { word: "Potential Energy", definition: "Stored energy possessed by an object due to its position or shape.", etymology: "From Latin 'potentia' (power).", funFact: "Gravitational potential energy converts into kinetic energy during freefall.", score: 15 },
  { word: "Power", definition: "Rate at which work is performed or energy is converted per unit time.", etymology: "From Latin 'posse' (to be able).", funFact: "One horsepower is equivalent to approximately 746 Watts.", score: 15 },
  { word: "Pressure", definition: "Continuous physical force exerted perpendicular to the surface of an object per unit area (P = F/A).", etymology: "From Latin 'pressura'.", funFact: "High heels exert higher pressure on floors than an elephant's foot due to tiny surface area!", score: 15 },
  { word: "Density", definition: "Mass per unit volume of a material substance (d = m/V).", etymology: "From Latin 'densus' (thick/compact).", funFact: "Osmium is the densest naturally occurring element on Earth.", score: 15 },
  { word: "Buoyancy", definition: "Upward fluid force supporting an object immersed in a liquid or gas.", etymology: "From Spanish 'boyar' (to float).", funFact: "Archimedes discovered that buoyant force equals the weight of displaced fluid!", score: 20 },
  { word: "Torque", definition: "Rotational force equivalent causing an object to rotate around an axis.", etymology: "From Latin 'torquere' (to twist).", funFact: "Using a longer wrench increases torque for turning stubborn bolts.", score: 20 },
  { word: "Vector", definition: "Quantity possessing both magnitude and direction.", etymology: "From Latin 'vector' (carrier).", funFact: "Force, velocity, and displacement are all vector quantities.", score: 15 },
  { word: "Scalar", definition: "Quantity fully described by magnitude alone without direction.", etymology: "From Latin 'scalaris' (ladder/scale).", funFact: "Temperature, mass, and energy are scalar quantities.", score: 15 },
  { word: "Wavelength", definition: "Distance between identical successive crests or troughs of a wave.", etymology: "From 'wave' + 'length'.", funFact: "Red light has longer wavelengths than blue light.", score: 15 },
  { word: "Frequency", definition: "Number of wave oscillations passing a fixed point per second, measured in Hertz (Hz).", etymology: "From Latin 'frequentia' (crowd/multitude).", funFact: "Human ears can hear sound frequencies from 20 Hz up to 20,000 Hz.", score: 15 },
  { word: "Amplitude", definition: "Maximum displacement of a wave oscillation from its equilibrium rest position.", etymology: "From Latin 'amplitudo' (wide extent).", funFact: "Sound wave amplitude determines loudness, while light amplitude determines brightness.", score: 15 },
  { word: "Refraction", definition: "Bending of a wave as it passes at an angle from one medium to another with different density.", etymology: "From Latin 'refringere' (break back).", funFact: "Refraction in raindrops splits sunlight into vivid rainbows!", score: 20 },
  { word: "Reflection", definition: "Change in wave direction at an interface returning the wave back into the original medium.", etymology: "From Latin 'reflectere' (bend back).", funFact: "The Law of Reflection states that angle of incidence equals angle of reflection.", score: 10 },
  { word: "Diffraction", definition: "Bending or spreading of waves around obstacles or through narrow gaps.", etymology: "From Latin 'diffringere' (shatter/break apart).", funFact: "Diffraction allows sound waves to bend around doorway corners so you can hear people around walls.", score: 20 },
  { word: "Electricity", definition: "Set of physical phenomena associated with the presence and motion of electric charge.", etymology: "From Greek 'elektron' (amber).", funFact: "Lightning bolts can reach temperatures hotter than the surface of the Sun!", score: 10 },
  { word: "Current", definition: "Rate of flow of electric charge through a conductor per unit time, measured in Amperes.", etymology: "From Latin 'currere' (to run).", funFact: "Conventional electric current flows from positive to negative terminals.", score: 15 },
  { word: "Voltage", definition: "Electric potential difference driving electric current through a circuit, measured in Volts.", etymology: "Named after Alessandro Volta, inventor of the electric battery.", funFact: "Volts measure the electrical 'push' force in a circuit.", score: 15 },
  { word: "Resistance", definition: "Opposition to the flow of electric current in a conductor, measured in Ohms.", etymology: "From Latin 'resistere' (hold back).", funFact: "Ohm's Law states Voltage = Current x Resistance (V = IR).", score: 15 },
  { word: "Electromagnet", definition: "Magnet created by running electric current through a coil of wire wrapped around an iron core.", etymology: "From 'electric' + 'magnet'.", funFact: "Superconducting electromagnets levitate high-speed Maglev trains!", score: 20 },
  { word: "Thermodynamics", definition: "Branch of physics dealing with heat, work, temperature, and energy transformations.", etymology: "From Greek 'therme' (heat) + 'dynamis' (power).", funFact: "The First Law of Thermodynamics states energy cannot be created or destroyed.", score: 25 },
  { word: "Entropy", definition: "Measure of thermal energy unavailable for work or measure of disorder in a system.", etymology: "From Greek 'en' (in) + 'trope' (transformation).", funFact: "The Second Law of Thermodynamics dictates total entropy of the universe always increases.", score: 25 }
];

// Astronomy dictionary terms
mergedData["astronomy-space"] = [
  { word: "Star", definition: "Luminous astronomical sphere of plasma held together by its own gravity, powered by nuclear fusion.", etymology: "From Old English 'steorra'.", funFact: "The Sun is a yellow dwarf star located 93 million miles from Earth.", score: 10 },
  { word: "Planet", definition: "Celestial body orbiting a star that is massive enough to be rounded by its own gravity and clear its orbit.", etymology: "From Greek 'planetes' (wanderer).", funFact: "Jupiter is so massive that all other solar system planets could fit inside it!", score: 10 },
  { word: "Galaxy", definition: "Gravitationally bound system of stars, stellar remnants, interstellar gas, dust, and dark matter.", etymology: "From Greek 'galaxias' (milky circle).", funFact: "The observable universe contains over 2 trillion galaxies!", score: 15 },
  { word: "Nebula", definition: "Enormous interstellar cloud of dust, hydrogen, helium, and ionized gases where stars are born.", etymology: "From Latin 'nebula' (cloud/mist).", funFact: "The Orion Nebula is a stellar nursery active 1,300 light-years from Earth.", score: 15 },
  { word: "Supernova", definition: "Colossal stellar explosion occurring during the last evolutionary stages of a massive star.", etymology: "From Latin 'super' (above) + 'nova' (new star).", funFact: "A single supernova can briefly outshine an entire galaxy of billions of stars!", score: 20 },
  { word: "Black Hole", definition: "Region of spacetime where gravity is so intense that nothing, not even light, can escape.", etymology: "Astronomical term coined by John Wheeler.", funFact: "The supermassive black hole at the center of the Milky Way is named Sagittarius A*.", score: 20 },
  { word: "Singularity", definition: "Point of infinite density and zero volume at the center of a black hole.", etymology: "From Latin 'singularis' (single/unique).", funFact: "At a singularity, known laws of physics cease to function.", score: 25 },
  { word: "Exoplanet", definition: "Planet located outside our solar system orbiting a distant star.", etymology: "From Greek 'exo' (outside) + Planet.", funFact: "Astronomers have confirmed over 5,000 exoplanets in our galaxy so far!", score: 20 },
  { word: "Spectroscopy", definition: "Study of light spectra emitted or absorbed by matter to determine stellar chemical composition.", etymology: "From Latin 'spectrum' + Greek 'skopein' (to look).", funFact: "Spectroscopy revealed that stars are mostly made of hydrogen and helium gas.", score: 25 },
  { word: "Parallax", definition: "Apparent displacement or shift in the position of a star viewed along two different lines of sight.", etymology: "From Greek 'parallaxis' (alternation).", funFact: "Parallax angle allows astronomers to directly calculate distance to nearby stars.", score: 20 },
  { word: "Luminosity", definition: "Total amount of electromagnetic energy emitted by a star per unit time.", etymology: "From Latin 'lumen' (light).", funFact: "Rigel in Orion is 120,000 times more luminous than our Sun!", score: 20 },
  { word: "Gravitational Wave", definition: "Ripples in spacetime caused by violent cosmic processes like colliding black holes.", etymology: "Predicted by Albert Einstein in 1916.", funFact: "LIGO detected gravitational waves for the first time in 2015 from black hole mergers!", score: 25 },
  { word: "Cosmic Microwave Background", definition: "Thermal radiation remnant left over from the Big Bang filling the universe.", etymology: "Discovered by Penzias and Wilson in 1964.", funFact: "CMB radiation provides compelling empirical proof of the Big Bang creation theory.", score: 25 },
  { word: "Dark Matter", definition: "Hypothetical form of matter that does not interact with light but exerts gravitational pull on visible galaxies.", etymology: "Coined by Fritz Zwicky in 1933.", funFact: "Dark matter makes up roughly 27% of the total mass-energy content of the universe!", score: 25 },
  { word: "Dark Energy", definition: "Mysterious force causing the accelerated expansion of the universe.", etymology: "Coined by Michael Turner in 1998.", funFact: "Dark energy accounts for about 68% of the total universe energy density!", score: 25 }
];

// Add copies for alias topic keys
mergedData["cell-biology"] = mergedData["organisation-organism"];
mergedData["genetics-dna"] = mergedData["inheritance"];
mergedData["photosynthesis-ecology"] = mergedData["plant-nutrition"];
mergedData["anatomy-physiology"] = mergedData["human-nutrition"];
mergedData["reproduction-plants"] = mergedData["reproduction"];

fs.writeFileSync(mergedDataPath, JSON.stringify(mergedData, null, 2));
console.log("Successfully updated merged_data.json with Chemistry, Physics, Astronomy and preset alias topics!");
